export const articles = [
  {
    slug: "exam-guide", category: "Start here", title: "The SIE exam, without the noise", description: "Understand the current format, what passing means, and the official sources that should anchor your plan.", related: ["eligibility-enrollment", "study-plan", "test-day"],
    body: `<h2>What the SIE measures</h2><p>The Securities Industry Essentials exam tests introductory knowledge of the securities industry: markets, products and their risks, trading and customer accounts, prohibited activities, and the regulatory framework. It is a foundation exam, not a license to conduct securities business.</p><h2>Know the current format</h2><p>The 2025 FINRA outline lists 75 scored multiple-choice items and 5 unidentified unscored pretest items, for 80 total. Candidates receive 1 hour 45 minutes. The passing standard is a scaled score of 70, and reference materials are not permitted.</p><h2>Study from the outline</h2><p>Use the official content outline as the map, then use textbooks, courses and original practice questions to build understanding. Do not rely on recalled or shared live exam content: FINRA treats exam questions as confidential.</p><div class="note"><strong>Important boundary</strong><p>Passing SIE can demonstrate foundational knowledge, but registration requires the applicable qualification exam, member-firm association and other requirements.</p></div>`
  },
  {
    slug: "eligibility-enrollment", category: "Enrollment", title: "Who can take the SIE and how enrollment works", description: "Separate open SIE eligibility from the sponsorship required for representative-level qualification exams.", related: ["exam-guide", "after-passing", "test-day"],
    body: `<h2>You can take SIE without firm sponsorship</h2><p>FINRA permits individuals age 18 or older to enroll for the SIE without being associated with a member firm. That makes it different from representative-level qualification exams, which generally require association and sponsorship.</p><h2>Choose the right enrollment route</h2><p>If you already work with a broker-dealer or investment adviser, FINRA advises consulting your firm before self-enrolling. A firm may need to submit enrollment through Form U4. Independent candidates can use FINRA's enrollment path.</p><h2>Plan the scheduling window</h2><p>Enrollment and scheduling are separate steps. Read the current FINRA and testing-provider instructions for the window, identification, testing mode, accommodations, cancellation and rescheduling rules.</p><h2>Use your exact identity</h2><p>Enter your legal identifying information consistently. Resolve differences before test day rather than assuming the test center can correct them.</p>`
  },
  {
    slug: "content-outline", category: "Exam blueprint", title: "Read the four SIE sections as one system", description: "Use FINRA's current weighting to allocate study time without ignoring smaller domains.", related: ["products-and-risks", "trading-accounts", "regulatory-framework"],
    body: `<h2>Section 1: capital markets</h2><p>FINRA allocates 16%, or 12 scored items, to market structure, regulators, participants, economic factors, offerings and market types.</p><h2>Section 2: products and risks</h2><p>The largest section is 44%, or 33 scored items. It covers equity and debt, options, packaged products, municipal securities, alternatives and risk concepts. Give it proportionate time, but do not turn the whole plan into product flashcards.</p><h2>Section 3: trading, accounts and prohibited activities</h2><p>This section carries 31%, or 23 scored items. Expect order and settlement concepts, returns, account types, customer communications, AML and conduct boundaries.</p><h2>Section 4: regulatory framework</h2><p>The final 9%, or 7 scored items, includes registration, continuing education and employee conduct. Smaller weight does not mean optional: a compact rules review can protect several points.</p>`
  },
  {
    slug: "products-and-risks", category: "Products", title: "Study securities products through risk and investor fit", description: "Connect product mechanics to interest-rate, credit, liquidity, market and tax considerations.", related: ["content-outline", "capital-markets", "practice-questions"],
    body: `<h2>Build a comparison frame</h2><p>For each product, identify ownership or creditor status, return source, priority, liquidity, major risks and any special tax treatment. A consistent frame makes differences easier to retrieve.</p><h2>Learn relationships, not isolated definitions</h2><p>Bond prices and yields move inversely; duration affects rate sensitivity; option value reacts to time and volatility; leverage changes both opportunity and loss. Explain the direction before calculating.</p><h2>Keep protection programs distinct</h2><p>FDIC and SIPC serve different roles and neither removes investment risk. Study what each protects, who it applies to and what it does not guarantee.</p><h2>Use suitability-style reasoning carefully</h2><p>SIE focuses on foundational knowledge, but scenarios still require matching facts to product risk. Avoid labeling a product as simply safe or risky without stating the relevant condition.</p>`
  },
  {
    slug: "capital-markets", category: "Markets", title: "Capital markets: follow the security from issuer to investor", description: "Organize issuers, underwriters, primary offerings, secondary trading and economic forces into a coherent map.", related: ["content-outline", "products-and-risks", "trading-accounts"],
    body: `<h2>Start with roles</h2><p>Distinguish issuers, underwriters, broker-dealers, market makers, investment advisers, transfer agents, custodians and regulators by the function they perform.</p><h2>Separate issuance from trading</h2><p>The primary market raises capital for an issuer. The secondary market lets investors trade existing securities. Trace where proceeds go and which disclosure or market mechanism matters.</p><h2>Connect policy to markets</h2><p>Interest rates, inflation, business cycles and fiscal or monetary actions can affect prices, yields and investor behavior. Focus on directional relationships rather than predictions.</p><h2>Review offering language</h2><p>Know the purpose of registration statements, prospectuses, exemptions, underwriting arrangements and offering periods at the level specified in the FINRA outline.</p>`
  },
  {
    slug: "trading-accounts", category: "Trading & accounts", title: "Trading and customer accounts: learn the operational chain", description: "Connect order types, quotes, settlement, returns, ownership and account documentation.", related: ["content-outline", "prohibited-activities", "test-day"],
    body: `<h2>Translate the order instruction</h2><p>Market, limit, stop and stop-limit orders trade certainty, price control and execution risk differently. State what triggers the order and what remains uncertain.</p><h2>Read the quote from both sides</h2><p>Bid is the price at which the market buys; ask is the price at which it sells. The spread affects transaction economics and helps distinguish principal from agency activity.</p><h2>Map the account ownership</h2><p>Individual, joint, custodial, retirement and trust accounts carry different control, beneficiary and documentation implications. Learn the purpose before memorizing paperwork.</p><h2>Keep returns and settlement practical</h2><p>Calculate total return from income plus price change, respect the units and distinguish trade date from settlement responsibilities. Recheck current settlement conventions from official materials.</p>`
  },
  {
    slug: "prohibited-activities", category: "Conduct", title: "Recognize prohibited conduct by the duty it breaks", description: "Study manipulation, material nonpublic information, customer funds and communication failures through clear boundaries.", related: ["trading-accounts", "regulatory-framework", "practice-questions"],
    body: `<h2>Ask whose interest is being harmed</h2><p>Manipulation distorts the market, misuse of material nonpublic information undermines fairness, and mishandling customer assets violates custody and trust boundaries. The violated duty often identifies the answer.</p><h2>Separate knowledge from action</h2><p>A scenario may test possession of information, its materiality, whether it is public, and what a person does with it. Do not jump to a label before checking each element.</p><h2>Protect customer assets and information</h2><p>Review commingling, borrowing, guarantees, privacy, cybersecurity awareness, AML escalation and suspicious-activity concepts at the level in the outline.</p><h2>Read communications in context</h2><p>Claims, omissions, projections and approval requirements depend on the audience and medium. Look for balanced presentation and prohibited assurances.</p>`
  },
  {
    slug: "regulatory-framework", category: "Regulation", title: "Build a clean map of the SIE regulatory framework", description: "Distinguish the SEC, FINRA, MSRB, state regulators and protection organizations by authority and purpose.", related: ["content-outline", "prohibited-activities", "after-passing"],
    body: `<h2>Start with jurisdiction</h2><p>The SEC is a federal regulator; FINRA is a self-regulatory organization for broker-dealers; the MSRB writes rules for the municipal securities market; state regulators enforce state securities laws. Do not collapse them into one generic regulator.</p><h2>Separate rulemaking from enforcement and protection</h2><p>Ask whether an entity writes rules, examines firms, enforces standards, insures bank deposits or helps return customer property after a broker-dealer failure.</p><h2>Connect registration to function</h2><p>Registration categories follow the work a person performs. Passing SIE is a corequisite foundation, not a stand-alone registration category or permission to perform regulated activity.</p><h2>Use current rules</h2><p>Registration and qualification requirements can change. Anchor this topic in FINRA Rule 1210 and the current outline instead of an old prep summary.</p>`
  },
  {
    slug: "study-plan", category: "Study method", title: "A four-week SIE study plan", description: "Move from the official blueprint to applied questions, mixed review and a calm final week.", related: ["content-outline", "practice-questions", "test-day"],
    body: `<h2>Week 1: build the map</h2><p>Read the outline, learn market participants and capital-market structure, and take a short diagnostic. Record uncertainty by section rather than chasing an early percentage.</p><h2>Week 2: products and risk</h2><p>Give the largest section the largest block of time. Compare equities, debt, options, funds, municipal products, alternatives and risk relationships using one repeatable framework.</p><h2>Week 3: operations and conduct</h2><p>Work through orders, settlement, accounts, AML, communications and prohibited activities. Add the regulatory framework, then begin mixed sets.</p><h2>Week 4: simulate and narrow</h2><p>Use timed practice and review every wrong answer and correct guess. In the last days, close the two weakest areas, verify logistics and protect sleep.</p>`
  },
  {
    slug: "practice-questions", category: "Study method", title: "Use SIE practice questions without memorizing noise", description: "Turn every question into a short diagnosis of the concept, cue and distractor.", related: ["study-plan", "products-and-risks", "mock-exams"],
    body: `<h2>Commit before checking</h2><p>Select an answer and state the reason. Immediate guessing followed by explanation-reading creates familiarity without reliable retrieval.</p><h2>Classify the miss</h2><p>Was the problem missing knowledge, a confused distinction, ignored wording, calculation error or time pressure? The repair depends on the cause.</p><h2>Review correct guesses</h2><p>A guessed correct answer is not stable mastery. Mark it and explain why the other options fail.</p><h2>Protect exam integrity</h2><p>Use independently written practice aligned to the outline. Do not seek recalled live questions; FINRA rules treat exam content as confidential.</p>`
  },
  {
    slug: "mock-exams", category: "Study method", title: "Make mock exams resemble decision pressure", description: "Use full-length practice to test pacing, retrieval and recovery—not just a score.", related: ["practice-questions", "study-plan", "test-day"],
    body: `<h2>Simulate the current structure</h2><p>Use a session that reflects the 105-minute time limit and broad four-section mix. Treat every item as scored because the five pretest questions are unidentified.</p><h2>Track pacing by checkpoints</h2><p>Choose a few time checkpoints rather than watching the clock after every item. Preserve a review buffer without rushing the first pass.</p><h2>Analyze after the score</h2><p>Group misses by official section and by error type. One cluster of product-risk errors needs different work from scattered reading mistakes.</p><h2>Do not over-test</h2><p>A mock exam is expensive practice. Alternate simulations with targeted repair so repeated tests measure changed knowledge rather than repeated exposure.</p>`
  },
  {
    slug: "test-day", category: "Test day", title: "SIE test-day execution", description: "Protect attention, time and logistics from check-in through the final review.", related: ["exam-guide", "mock-exams", "after-passing"],
    body: `<h2>Verify the appointment at the source</h2><p>Confirm identification, arrival or online check-in, testing rules and current provider instructions. Policies can change, so use your appointment confirmation and FINRA-linked provider.</p><h2>Read for the tested distinction</h2><p>Identify the actor, product, account, instruction and rule boundary before selecting. Watch qualifiers such as except, most and best.</p><h2>Use a controlled first pass</h2><p>Answer clear items, mark uncertain ones and maintain the pace you practiced. There is no penalty for guessing, so do not leave an item unanswered.</p><h2>Keep the result in perspective</h2><p>A passing result is meaningful progress, not authorization to engage in securities business. Save your records and understand the next qualification step relevant to your career.</p>`
  },
  {
    slug: "after-passing", category: "Career path", title: "What passing the SIE does—and does not—do", description: "Understand result validity, firm association and the qualification exam that may come next.", related: ["eligibility-enrollment", "regulatory-framework", "exam-guide"],
    body: `<h2>Passing is a foundation</h2><p>FINRA states that passing SIE alone does not qualify someone for registration or securities activity. Registration generally requires association with a member firm, the applicable representative-level qualification exam and other requirements.</p><h2>Know the four-year rule</h2><p>Rule 1210 provides that a person may need to retake SIE when four or more years have elapsed since passing or since last being registered as a representative, whichever occurred later. Special circumstances can affect the calculation.</p><h2>Match the next exam to the function</h2><p>Series 6, Series 7, Series 79 and other exams correspond to different activities. A firm determines the appropriate registration and files the required application.</p><h2>Keep claims precise</h2><p>On a résumé, describe the result accurately. Do not claim to be licensed, FINRA-registered or authorized solely because you passed SIE.</p>`
  },
  {
    slug: "retake-strategy", category: "Retake", title: "Retaking the SIE: use the waiting period well", description: "Follow current Rule 1210 and rebuild weak areas before choosing the next appointment.", related: ["practice-questions", "mock-exams", "study-plan"],
    body: `<h2>Check the current rule before booking</h2><p>As checked on September 18, 2026, FINRA Rule 1210 states a 15-calendar-day wait after a failed qualification exam and a 60-calendar-day wait after three or more successive failures within two years. The rule applies to SIE candidates, including individuals who are not associated persons.</p><h2>Diagnose, then schedule</h2><p>Use your performance feedback and memory of difficulty categories—not recalled questions—to identify gaps. Delay a new appointment if the waiting period ends before the repair is complete.</p><h2>Change the method</h2><p>If the first plan relied on reading, add retrieval and explanation. If pacing failed, practice timed blocks. If misses cluster in one official section, rebuild its concepts before returning to mixed work.</p><h2>Recheck logistics and fees</h2><p>Enrollment, fees and provider policies may change. Confirm them through current FINRA sources before paying or rescheduling.</p>`
  }
];
