import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { articles } from "../content/articles.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "dist");
const repo = "sie-prep-by-rushlabs-web";
const origin = `https://mcyj.github.io/${repo}`;
const base = `/${repo}`;
const checkedAt = "2026-09-18";
const finraPage = "https://www.finra.org/registration-exams-ce/qualification-exams/securities-industry-essentials-exam";
const finraOutline = "https://www.finra.org/sites/default/files/2025-10/SIE_Content_Outline.pdf";
const finraExams = "https://www.finra.org/registration-exams-ce/qualification-exams";
const finraEnroll = "https://www.finra.org/registration-exams-ce/qualification-exams/enroll";
const finraRule = "https://www.finra.org/rules-guidance/rulebooks/finra-rules/1210";
const playUrl = "https://play.google.com/store/apps/details?id=app.mcyj.examprep.glb0005";
const supportEmail = "june1012june@gmail.com";

const escapeHtml = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
async function put(path, contents) { const target = join(out, path); await mkdir(dirname(target), { recursive: true }); await writeFile(target, contents); }

function nav() {
  return `<header class="site-header"><a class="brand" href="${base}/en/"><img src="${base}/assets/app-icon.svg" width="42" height="42" alt=""><span>SIE<br><strong>Exam Prep</strong></span></a><nav aria-label="Primary"><a href="${base}/en/guides/">Study guides</a><a href="${base}/en/faq/">FAQ</a><a href="${base}/en/support/">Support</a></nav></header>`;
}
function footer() {
  return `<footer><div><strong>SIE Prep by RushLabs</strong><p>Independent study support from RushLabs. Not affiliated with or endorsed by FINRA.</p></div><nav aria-label="Legal"><a href="${base}/en/privacy/">Privacy</a><a href="${base}/en/terms/">Terms</a><a href="${base}/en/support/">Support</a><a href="${base}/en/contact/">Contact</a></nav><p class="source-note">Official exam details checked ${checkedAt}. Current FINRA rules, outline and provider instructions control.</p></footer>`;
}
function layout({ title, description, path, body, type = "website", jsonLd = null }) {
  const canonical = `${origin}${path}`;
  const schema = jsonLd ? `<script type="application/ld+json">${JSON.stringify(jsonLd).replaceAll("<", "\\u003c")}</script>` : "";
  return `<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en-US" href="${canonical}"><link rel="alternate" hreflang="x-default" href="${canonical}"><meta property="og:type" content="${type}"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="SIE Prep by RushLabs"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#2d281e"><link rel="icon" href="${base}/assets/app-icon.svg"><link rel="stylesheet" href="${base}/assets/styles.css">${schema}</head><body><a class="skip" href="#main">Skip to content</a><div class="page-shell">${nav()}<main id="main">${body}</main>${footer()}</div></body></html>`;
}
function storeButtons(label = "Get the app") {
  return `<div class="store-block" aria-labelledby="store-heading"><p class="eyebrow" id="store-heading">${label}</p><div class="store-row"><a class="play-badge" href="${playUrl}" aria-label="Get SIE Prep by RushLabs on Google Play"><img src="${base}/assets/google-play-badge.png" width="194" height="75" alt="Get it on Google Play"></a><span class="store-button disabled" aria-label="Apple App Store coming soon"><span aria-hidden="true">●</span><span><small>App Store</small>Coming soon</span></span></div><p class="store-note">Available on Google Play. The iOS version is still awaiting verified publication.</p></div>`;
}

const homeBody = `<section class="hero"><div class="hero-copy"><p class="eyebrow">Securities Industry Essentials</p><h1>Learn the market.<br><span>Know the boundary.</span></h1><p class="lede">Focused SIE practice across capital markets, products and risks, trading, customer accounts, prohibited conduct and regulation.</p>${storeButtons()}</div><div class="hero-ledger" aria-label="Current SIE exam overview"><div><span>Items</span><strong>75 + 5</strong><small>scored + unidentified pretest</small></div><div><span>Time</span><strong>105 min</strong><small>computer-delivered</small></div><div><span>Standard</span><strong>70</strong><small>scaled passing score</small></div><div><span>Fee</span><strong>$100</strong><small>recheck before enrollment</small></div></div><div class="phone-stage"><img src="${base}/assets/screenshots/question.png" width="393" height="852" alt="SIE Prep by RushLabs practice question screen"></div></section>
<section class="ticker" aria-label="App and exam highlights"><span>500 original practice questions</span><span>4 official sections</span><span>Local-first progress</span><span>No account required</span></section>
<section class="split section"><div><p class="eyebrow">The blueprint</p><h2>Products carry 44%. Decisions still cross every section.</h2><p>The current outline allocates 33 of 75 scored items to products and their risks, 23 to trading, accounts and prohibited activities, 12 to capital markets, and 7 to the regulatory framework.</p><a class="text-link" href="${base}/en/guides/content-outline/">Read the content outline guide <span aria-hidden="true">→</span></a></div><div class="allocation"><div style="--share:44"><span>Products & risks</span><strong>44%</strong></div><div style="--share:31"><span>Trading, accounts & conduct</span><strong>31%</strong></div><div style="--share:16"><span>Capital markets</span><strong>16%</strong></div><div style="--share:9"><span>Regulatory framework</span><strong>9%</strong></div><p class="source-note">FINRA 2025 Content Outline · checked ${checkedAt}</p></div></section>
<section class="section"><div class="section-heading"><div><p class="eyebrow">Inside the app</p><h2>Practise the distinction. Track the pattern.</h2></div><p>Work through original questions, run mixed mock exams and use progress history to return to weak areas.</p></div><div class="screens"><figure><img loading="lazy" src="${base}/assets/screenshots/question.png" width="393" height="852" alt="A SIE practice question"><figcaption>Commit to the rule or relationship.</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/practice-tests.png" width="393" height="852" alt="SIE practice test list"><figcaption>Move into full-section practice.</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/progress.png" width="393" height="852" alt="SIE learning progress screen"><figcaption>Use the pattern behind the score.</figcaption></figure></div></section>
<section class="section guide-preview"><div class="section-heading"><div><p class="eyebrow">Free study guides</p><h2>Build a market map, not a pile of terms.</h2></div><a class="text-link" href="${base}/en/guides/">Browse all ${articles.length} guides <span aria-hidden="true">→</span></a></div><div class="guide-grid">${articles.slice(0, 6).map((a, i) => `<a class="guide-card" href="${base}/en/guides/${a.slug}/"><span>${String(i + 1).padStart(2, "0")} · ${a.category}</span><h3>${a.title}</h3><p>${a.description}</p></a>`).join("")}</div></section>
<section class="section faq-teaser"><div><p class="eyebrow">Passing and registration</p><h2>SIE is a foundation—not a securities license.</h2></div><div><p>Passing alone does not authorize securities activity or qualify someone for FINRA registration. The applicable qualification exam, firm association and other requirements still matter.</p><a class="text-link" href="${base}/en/faq/">Read the FAQ <span aria-hidden="true">→</span></a></div></section>
<section class="final-cta"><h2>Make the relationship explainable.</h2><p>SIE Prep by RushLabs is available now on Google Play.</p>${storeButtons("App availability")}</section>`;

const softwareSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "SIE Prep by RushLabs", applicationCategory: "EducationalApplication", operatingSystem: "Android", description: "Independent SIE practice and mock-exam app.", url: `${origin}/en/`, downloadUrl: playUrl, publisher: { "@type": "Organization", name: "RushLabs" }, offers: { "@type": "Offer", price: "0", priceCurrency: "USD", availability: "https://schema.org/InStock" } };
const guidesBody = `<section class="page-intro"><p class="eyebrow">Study library</p><h1>SIE study guides</h1><p>Original preparation guidance grounded in current FINRA sources. Exam rules, fees and registration requirements can change; verify dated facts before acting.</p></section><section class="guide-grid all-guides">${articles.map((a) => `<a class="guide-card" href="${base}/en/guides/${a.slug}/"><span>${a.category}</span><h2>${a.title}</h2><p>${a.description}</p></a>`).join("")}</section><aside class="official-source"><h2>Official information first</h2><p>Use these guides for study structure. Use FINRA for the current outline, enrollment, fee, administration and qualification rules.</p><div><a href="${finraOutline}">SIE Content Outline</a><a href="${finraPage}">FINRA SIE page</a><a href="${finraEnroll}">Enroll for an exam</a><a href="${finraRule}">FINRA Rule 1210</a></div></aside>`;

function articlePage(article) {
  const related = article.related.map((slug) => articles.find((item) => item.slug === slug)).filter(Boolean);
  const body = `<article class="article"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${base}/en/">Home</a><span>/</span><a href="${base}/en/guides/">Guides</a><span>/</span><span aria-current="page">${article.category}</span></nav><header><p class="eyebrow">${article.category}</p><h1>${article.title}</h1><p class="lede">${article.description}</p><p class="article-meta">Reviewed against official FINRA sources · ${checkedAt}</p></header><div class="article-layout"><div class="article-copy">${article.body}<section class="sources"><h2>Official sources</h2><ul><li><a href="${finraOutline}">FINRA SIE Content Outline</a></li><li><a href="${finraPage}">FINRA SIE page</a></li><li><a href="${finraExams}">FINRA Qualification Exams</a></li><li><a href="${finraRule}">FINRA Rule 1210</a></li></ul><p>Confirm current fees, enrollment, accommodations, provider instructions and registration requirements before acting.</p></section></div><aside class="article-aside"><img src="${base}/assets/app-icon.svg" width="88" height="88" alt="SIE Prep by RushLabs icon"><h2>Practise the distinction</h2><p>Use original questions, explanations, saved items and mock exams in the Android app.</p><a class="status-pill live" href="${playUrl}">Available on Google Play</a></aside></div><section class="related"><p class="eyebrow">Continue studying</p><div class="guide-grid">${related.map((item) => `<a class="guide-card" href="${base}/en/guides/${item.slug}/"><span>${item.category}</span><h3>${item.title}</h3></a>`).join("")}</div></section></article>`;
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, datePublished: checkedAt, dateModified: checkedAt, inLanguage: "en-US", author: { "@type": "Organization", name: "RushLabs" }, publisher: { "@type": "Organization", name: "RushLabs" }, mainEntityOfPage: `${origin}/en/guides/${article.slug}/` };
  return layout({ title: `${article.title} | SIE Prep by RushLabs`, description: article.description, path: `/en/guides/${article.slug}/`, type: "article", body, jsonLd: schema });
}

const faqItems = [
  ["Is this an official FINRA app?", "No. It is independently produced by RushLabs and is not affiliated with or endorsed by FINRA or a securities regulator."],
  ["What is the current SIE format?", "The 2025 FINRA outline lists 75 scored questions plus 5 unidentified unscored pretest questions, 105 minutes, no reference materials and a scaled passing score of 70."],
  ["Does passing the SIE make me licensed?", "No. Passing SIE alone does not qualify someone for FINRA registration or authorize securities activity. The applicable qualification exam, member-firm association and other requirements still apply."],
  ["What does the app include?", "The current listing describes 500 independently authored questions, explanations, mock exams, bookmarks, local progress and an optional Lock Quiz."],
  ["Does the app reproduce live exam questions?", "No. It contains independently authored study material and does not claim to reproduce secured examination questions."],
  ["Do I need a RushLabs account?", "No. The current app is local-first and does not require a RushLabs account."],
  ["Is the iOS app available?", "Public iOS availability is not currently verified. The site therefore shows the App Store version as Coming soon."],
  ["How long is an SIE result valid?", "Rule 1210 generally requires a person to retake SIE when four or more years have elapsed since passing or since last being registered as a representative, whichever occurred later. Check the current rule for your circumstances."],
  ["Where should I verify current rules?", "Use FINRA for the current outline, enrollment, fee, administration, retake and registration requirements."],
];
const faqBody = `<section class="page-intro"><p class="eyebrow">Questions & answers</p><h1>Know the boundary before you begin.</h1><p>Current exam facts, app scope and the difference between passing and registration.</p></section><section class="faq-list">${faqItems.map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join("")}</section>`;
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };

const privacyBody = `<article class="policy"><p class="eyebrow">Legal</p><h1>Privacy Policy</h1><p class="article-meta">Effective: September 18, 2026</p><h2>Operator</h2><p>RushLabs operates SIE Prep by RushLabs (GLB-0005). Privacy questions: <a href="mailto:${supportEmail}">${supportEmail}</a>.</p><h2>Learning information</h2><p>The current app does not require a RushLabs account. Practice answers, bookmarks, progress, review history and preferences are stored locally on your device according to the current app implementation and listing.</p><h2>Purchases</h2><p>Google Play or Apple App Store handles payment information under its own policies. RushLabs does not receive card details through the app. Store product and transaction information may be used to determine access.</p><h2>Notifications and Lock Quiz</h2><p>Lock Quiz is optional. Question text remains hidden on the lock screen until you explicitly enable the feature. Device notification controls remain available to you.</p><h2>Support messages</h2><p>If you contact support, RushLabs receives what you voluntarily send. Do not send passwords, payment details, purchase tokens, receipts or private learning backups.</p><h2>This website</h2><p>This static website does not use analytics, advertising cookies, accounts or contact forms. External destinations apply their own privacy practices.</p></article>`;
const termsBody = `<article class="policy"><p class="eyebrow">Legal</p><h1>Terms of Use</h1><p class="article-meta">Effective: September 18, 2026</p><h2>Independent study aid</h2><p>The app is an independent exam-preparation product. It is not affiliated with or endorsed by FINRA or a regulator, and it does not reproduce secured examination questions.</p><h2>No professional authorisation</h2><p>Practice results and passing the SIE do not by themselves grant a license, FINRA registration or authority to conduct securities business. Current FINRA rules and firm requirements control.</p><h2>Personal use and accuracy</h2><p>Use original learning material for personal study. Laws, regulations, tax rules and exam policies can change. Current official sources control over summaries in the app or website.</p><h2>Store purchases</h2><p>Purchase only from the product name, duration, enabled features and full localised price shown in the Store-backed confirmation. Manage renewal, cancellation and refund requests through the purchasing Store account. Deleting the app does not cancel a subscription.</p><h2>Support</h2><p>Contact <a href="mailto:${supportEmail}">${supportEmail}</a>. These terms do not limit rights that cannot lawfully be excluded.</p></article>`;
const supportBody = `<section class="page-intro"><p class="eyebrow">App support</p><h1>Tell us what happened.</h1><p>Include the app name, device OS, app version and a short description. Screenshots help when they contain no private information.</p><a class="primary-button" href="mailto:${supportEmail}?subject=SIE%20Prep%20support">Email RushLabs support</a></section><section class="support-grid"><div><h2>Protect private information</h2><p>Do not send passwords, card information, purchase tokens, receipts or private learning backups.</p></div><div><h2>Purchases</h2><p>Use the purchasing Store account and Restore purchases where supported. Manage cancellation or refunds through the Store.</p></div><div><h2>Exam and registration</h2><p>Use FINRA for exam administration, enrollment and registration requirements.</p></div></section>`;
const contactBody = `<section class="page-intro contact"><p class="eyebrow">Contact</p><h1>RushLabs</h1><p>For app support, privacy questions or factual corrections:</p><a class="contact-email" href="mailto:${supportEmail}">${supportEmail}</a><p class="source-note">Do not email passwords, payment details, purchase tokens, receipts or private learning data.</p></section>`;

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
await cp(join(root, "assets"), join(out, "assets"), { recursive: true });
await cp(join(root, ".nojekyll"), join(out, ".nojekyll"));
await cp(join(root, "assets", "app-icon.svg"), join(out, "favicon.svg"));
await cp(join(root, "styles.css"), join(out, "assets", "styles.css"));
await put("index.html", `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SIE Prep by RushLabs</title><meta name="description" content="Independent SIE practice and study guides."><meta http-equiv="refresh" content="0;url=./en/"><link rel="canonical" href="${origin}/en/"><script>location.replace('./en/')</script></head><body><main id="main"><p><a href="./en/">Continue to SIE Prep by RushLabs</a></p></main></body></html>`);
await put("en/index.html", layout({ title: "SIE Prep by RushLabs | Practice questions and study guides", description: "Prepare for the SIE with original practice questions, explanations, mock exams and source-checked study guides.", path: "/en/", body: homeBody, jsonLd: softwareSchema }));
await put("en/guides/index.html", layout({ title: "SIE study guides", description: "Original SIE study guides for the exam outline, capital markets, products, trading, regulation, study strategy and mock exams.", path: "/en/guides/", body: guidesBody }));
for (const article of articles) await put(`en/guides/${article.slug}/index.html`, articlePage(article));
await put("en/faq/index.html", layout({ title: "FAQ | SIE Prep by RushLabs", description: "Answers about the SIE exam, registration boundary, app scope, privacy and Store availability.", path: "/en/faq/", body: faqBody, jsonLd: faqSchema }));
await put("en/privacy/index.html", layout({ title: "Privacy Policy | SIE Prep by RushLabs", description: "Privacy information for the SIE Prep by RushLabs app and website.", path: "/en/privacy/", body: privacyBody }));
await put("en/terms/index.html", layout({ title: "Terms of Use | SIE Prep by RushLabs", description: "Terms for SIE Prep by RushLabs, independent learning content and Store purchases.", path: "/en/terms/", body: termsBody }));
await put("en/support/index.html", layout({ title: "Support | SIE Prep by RushLabs", description: "Get help with SIE Prep by RushLabs, purchases, local progress and app issues.", path: "/en/support/", body: supportBody }));
await put("en/contact/index.html", layout({ title: "Contact RushLabs | SIE Prep by RushLabs", description: "Contact RushLabs about SIE Prep by RushLabs support, privacy or factual corrections.", path: "/en/contact/", body: contactBody }));
await put("404.html", layout({ title: "Page not found | SIE Prep by RushLabs", description: "The requested page could not be found.", path: "/404.html", body: `<section class="page-intro"><p class="eyebrow">404</p><h1>That page is not in this outline.</h1><p>The study guides and app information are still available.</p><a class="primary-button" href="${base}/en/">Return home</a></section>` }));
const urls = ["/en/", "/en/guides/", ...articles.map((a) => `/en/guides/${a.slug}/`), "/en/faq/", "/en/privacy/", "/en/terms/", "/en/support/", "/en/contact/"];
await put("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((path) => `  <url><loc>${origin}${path}</loc><lastmod>${checkedAt}</lastmod></url>`).join("\n")}\n</urlset>\n`);
await put("robots.txt", `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`Built ${urls.length} indexable pages in ${out}`);
